[workspace]
members = ["client", "server", "common/zkp_protobuf"]

[workspace.dependencies]
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
tonic = "0.10.2"
prost = "0.12"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
